---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-test
  name: front-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-test
  template:
    metadata:
      labels:
        app: front-test
    spec:
      containers:
      - image: wuzekai/front-test:latest
        #imagePullPolicy: Never
        name: front-test
        ports:
        - containerPort: 5100
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-test
  name: front-test
spec:
  ports:
  - port: 5100
    protocol: TCP
    targetPort: 5100
    nodePort: 32002
  selector:
    app: front-test
  type: NodePort